Enhance workflows and update script for improved error handling and clarity

diff --git a/.github/workflows/nightly-update.yml b/.github/workflows/nightly-update.yml
--- a/.github/workflows/nightly-update.yml
+++ b/.github/workflows/nightly-update.yml
@@ -34,7 +34,7 @@ jobs:
       - name: Get database_file from config.yaml
         id: get-database-file
         run: |
-          DATABASE_FILE=$(yq '.database_file' config.yaml)
+          DATABASE_FILE=$(yq -r '.database_file' config.yaml)
           if [ -z "$DATABASE_FILE" ]; then
             echo "Error: database_file not found in config.yaml"
             exit 1
@@ -44,7 +44,7 @@ jobs:
           DATABASE_FILE: ""
 
       # Step 6: Download database_file and checksum file from S3
-      - name: Config S3
+      - name: Config S3 and get MD5 file
         run: |
           echo "[default]" > ~/.s3cfg
           echo "access_key = $CF_R2_PUBLIC_BUCKET_ACCESS_KEY" >> ~/.s3cfg
@@ -57,6 +57,7 @@ jobs:
             echo "Error: Bucket is not available."
           exit 1
           fi
+          s3cmd get s3://public/$DATABASE_FILE.md5 $DATABASE_FILE.md5 || echo "Checksum file not found"
         env:
           CF_R2_PUBLIC_BUCKET_ACCESS_KEY: ${{ secrets.CF_R2_PUBLIC_BUCKET_ACCESS_KEY }}
           CF_R2_PUBLIC_BUCKET_SECRET_KEY: ${{ secrets.CF_R2_PUBLIC_BUCKET_SECRET_KEY }}
diff --git a/.github/workflows/run-script.yml b/.github/workflows/run-script.yml
--- a/.github/workflows/run-script.yml
+++ b/.github/workflows/run-script.yml
@@ -43,7 +43,7 @@ jobs:
           DATABASE_FILE: ""
 
       # Step 6: Download database_file and checksum file from S3
-      - name: Config S3
+      - name: Config S3 and get MD5 file
         run: |
           echo "[default]" > ~/.s3cfg
           echo "access_key = $CF_R2_PUBLIC_BUCKET_ACCESS_KEY" >> ~/.s3cfg
@@ -56,6 +56,7 @@ jobs:
             echo "Error: Bucket is not available."
           exit 1
           fi
+          s3cmd get s3://public/$DATABASE_FILE.md5 $DATABASE_FILE.md5 || echo "Checksum file not found"
         env:
           CF_R2_PUBLIC_BUCKET_ACCESS_KEY: ${{ secrets.CF_R2_PUBLIC_BUCKET_ACCESS_KEY }}
           CF_R2_PUBLIC_BUCKET_SECRET_KEY: ${{ secrets.CF_R2_PUBLIC_BUCKET_SECRET_KEY }}
